project:
  type: website

website:
  title: "phuse-datasetjson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: paper.qmd
        text: Paper
      - href: slides.qmd
        text: Presentation
  page-footer: 
    left: "Created using [Quarto](https://quarto.org/docs/websites/).

format:
  html:
    theme:
      - Sandstone
    css: styles.css
    toc: true



