on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish Slides

jobs:
  build-deploy-slides:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install libcurl system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - name: Install R dependencies
        run: |
          R -e 'install.packages(c("rmarkdown", "knitr", "datasetjson", "tibble"), repos = "https://cran.rstudio.com/")'

      - name: Render and Publish slides.qmd
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: slides.qmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render and Publish slides_long.qmd
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: slides_long.qmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
